environment:
  matrix:
    - nodejs_version: 0.10

platform:
# mapnik 64 bit is almost ready but not yet
#  - x64
  - x86

environment:
  MapboxAccessToken:
    secure: 01rO70zKIKzh2l8htHugNS3cCk9u3LfTu2SXojFaYkveumhZRDgRrH/BroS+fIv8T6YB5l0P2nvKAjqhdDW2yuaLWGIB5KdBmhywp4dXa0g=

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - node -e "console.log('node version ' + process.version + ', architecture ' + process.arch);"
  - npm install
  - npm test

build: OFF

test: OFF

test_script: OFF

deploy: OFF
