environment:
  matrix:
    - nodejs_version: 0.10
    # not working yet, will hit this later (dane)
    #- nodejs_version: 0.11.13
  MapboxAccessToken:
    secure: 01rO70zKIKzh2l8htHugNS3cCk9u3LfTu2SXojFaYkveumhZRDgRrH/BroS+fIv8T6YB5l0P2nvKAjqhdDW2yuaLWGIB5KdBmhywp4dXa0g=

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - ps: Start-FileDownload "https://mapnik.s3.amazonaws.com/dist/dev/VS-2014-runtime/vcredist_$env:Platform.exe"
  - .\vcredist_%platform%.exe /q /norestart
  - npm install mapnik@3.1.2
  - npm install
  - npm test

build: OFF
test: OFF
deploy: OFF
